### ISSUE TITLE
KeyError: 'token'

### ISSUE THREAD

**Issue by TickledOnions** [useragents/Funcaptcha-Audio-Solver#13]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Funcaptcha-Audio-Solver-main\Funcaptcha-Audio-Solver-main\main.py", line 27, in <module>
    captcha_token = solve_captcha()
                    ^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\Funcaptcha-Audio-Solver-main\Funcaptcha-Audio-Solver-main\main.py", line 14, in solve_captcha
    answer = funcap.solve()
             ^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\Funcaptcha-Audio-Solver-main\Funcaptcha-Audio-Solver-main\funcaptcha_solver.py", line 225, in solve
    session_token, response, captcha_token = self.main()
                                             ^^^^^^^^^^^
  File "C:\Users\User\Downloads\Funcaptcha-Audio-Solver-main\Funcaptcha-Audio-Solver-main\funcaptcha_solver.py", line 208, in main
    session_token, captcha_token = self.get_session_token()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\Funcaptcha-Audio-Solver-main\Funcaptcha-Audio-Solver-main\funcaptcha_solver.py", line 41, in get_session_token
    captcha_token = r.json()["token"]
                    ~~~~~~~~^^^^^^^^^
KeyError: 'token'

**Comment by zhaobijun** [comment]
这个接口是否免费使用呢

**Comment by AhmedWageeeh** [comment]
code is died!!

**Comment by zhaobijun** [comment]
可以帮忙我吗

在 2023-02-26 09:32:41，AhmedWageh ***@***.***> 写道：


code is died!!

**Comment by luxkatana** [comment]
Yeah, it is unmaintained.
